### ISSUE TITLE
Bruh there's no MCMMO

### ISSUE THREAD

**Issue by Jakeybobble** [bloofirephoenix/ChickenCubeIssues#3]
I wanna cut down dem trees
I wanna dig out dat dirt
I wanna slice and dice
Acrobatics would be nice.
Please give me MCMMO
It would be great, fo sho.
Now I leave you with this message.
bruh gamer lamer

**Comment by bloofirephoenix** [comment]
so far it seems people are not *fully* against it.

**Comment by bloofirephoenix** [comment]
currently uploaded to unstable branch
